
CREATE TABLE IF NOT EXISTS `execution_report` (
  `order_id` varchar(255) NOT NULL,
  `avg_px` int(11) NULL,
  `cl_ordid` varchar(255) DEFAULT NULL,
  `clientid` varchar(255) DEFAULT NULL,
  `cum_qty` int(11) NULL,
  `cumm_commission` int(11) NULL,
  `cxl_rej_reason` varchar(255) DEFAULT NULL,
  `escrow_restricted` bit(1) NULL,
  `exec_id` varchar(255) DEFAULT NULL,
  `exec_refid` varchar(255) DEFAULT NULL,
  `exec_type` int DEFAULT NULL,
  `fee` bigint(20) NULL,
  `last_commission` int(11) NULL,
  `last_liquidity_ind` int DEFAULT NULL,
  `last_px` int(11) NULL,
  `last_qty` int(11) NULL,
  `leaves_escrow` bigint(20) NULL,
  `leaves_qty` int(11) NULL,
  `mass_status_reqid` varchar(255) DEFAULT NULL,
  `ord_rej_reason` int DEFAULT NULL,
  `ord_status` int DEFAULT NULL,
  `ord_status_reqid` varchar(255) DEFAULT NULL,
  `ord_type` int DEFAULT NULL,
  `order_qty` int(11) NULL,
  `orig_cl_ordid` varchar(255) DEFAULT NULL,
  `orig_escrow` bigint(20) NULL,
  `peg_offset` bigint(20) NULL,
  `peg_price_type` int DEFAULT NULL,
  `peg_scope` int DEFAULT NULL,
  `pegged_price` int(11) NULL,
  `price` int(11) NULL,
  `secondary_order_id` bigint(20) NULL,
  `seq_num` bigint(20) NULL,
  `side` int DEFAULT NULL,
  `stop_px` int(11) NULL,
  `submit_time` datetime DEFAULT NULL,
  `symbol` varchar(255) DEFAULT NULL,
  `time_in_force` int DEFAULT NULL,
  `total_num_reports` int(11) NULL,
  `trade_id` varchar(255) DEFAULT NULL,
  `transact_time` datetime DEFAULT NULL,
  `trd_matchid` varchar(255) DEFAULT NULL,
  `trigger_price_type` int DEFAULT NULL,
  PRIMARY KEY (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
