spring:
  application:
    name: OrderManager
  jpa:
    generate-ddl: true
    show-sql: true
management:
  cloudfoundry:
    skip-ssl-validation: true
  security:
    enabled: false
        
security:
  basic:
    enabled: false

logging:
  level:
    io:
      pivotal:
        om: DEBUG
config:
  rate: 1
